name: Deploy Assets to S3

on:
  push:
    branches:
      - master

jobs:
  s3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.16.3]
    env:
      CI: true
      AWS_S3_BUCKET: t2hfe-dev-assets
      AWS_REGION: ap-southeast-1

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: build
      run: |
        npm run build
        npm run export || exit 0
    - name: clean empty directories
      run: find ./out -type d -empty -delete
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --cache-control public,max-age=31536000,immutable
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'out'
